### PR TITLE
Support für Contao 4.9 und Contao 4.13

### PR DESCRIPTION
**Pull request by a-kehr**

### CODE REVIEW

**Comment by plorenz-etes** [comment]
Could this please be merged and released? :) We've got a customer using this extension and he would like to upgrade to 4.13.

**Comment by plorenz-etes** [comment]
Anybody there? @dmolineus

**Comment by a-kehr** [comment]
@plorenz-etes mit einer kleinen Spende würde es beschleunigen.
https://contao-bootstrap.de/contao-4-13-kompatibilitaet.html

**Comment by dmolineus** [comment]
Thanks @kehr-solutions. Meanwhile manually merged and released as 2.1.0

**Pull request closed without merging**
